# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: release

on: 
  push:
    tags:
      - '*'

jobs:
  build:

    runs-on: windows-latest
    defaults:
      run:
        shell: cmd

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        global-json-file: global.json

    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build -c Release --no-restore -p:GeneratePackageOnBuild=true

    - run: dotnet nuget push -s https://api.nuget.org/v3/index.json -k "$env:NUGET_KEY" WS2_32.Win32Metadata.*.nupkg
      shell: pwsh
      env:
        NUGET_KEY: ${{ secrets.NUGET_KEY }}
      working-directory: src/bin/Release

    - uses: actions/upload-artifact@main
      with:
        name: ws2_32.winmd
        path: src/winmd/ws2_32.winmd

    - uses: actions/upload-artifact@main
      with:
        name: Nuget package
        path: src/bin/Release/WS2_32.Win32Metadata.*.nupkg
